name: nice_today_weather
description: "A weather application with robust features and clean architecture"
publish_to: 'none'
version: 1.0.6

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  
  # Weather API
  dio: ^5.4.1
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # UI Components
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Add this line
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/icons/weather/
    - assets/images/google_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
